#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") command
Execute TypeORM migration CLI commands in AWS ECS.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    elif [[ -z "${1}" ]]; then
        docker-compose \
            run --rm ecsmigrate \
            run migration:run
    else
        docker-compose \
            run --rm server \
            run migration:"${*}"
    fi
fi
