#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") command
Run a CLI task in ECS Fargate.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [ "${1:-}" = "--help" ] || [ "$#" -eq 0 ]; then
        usage
    else
        docker-compose run --rm ecsmigrate "$@"
    fi
fi
