#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run a CLI task in ECS Fargate.
"
}

function get_aws_vpc_config() {
    local SUBNET_IDS
    local SECURITY_GROUP_IDS
    SUBNET_IDS=$(
        aws ec2 describe-subnets \
            --filter "Name=tag:Project,Values=DistrictBuilder" \
            --filter "Name=tag:Environment,Values=Staging" \
            --filter "Name=tag:Name,Values=PrivateSubnet" \
            --query "Subnets[*].SubnetId"
    )
    SECURITY_GROUP_IDS=$(
        aws ec2 describe-security-groups \
            --filter "Name=group-name,Values=sgStagingAppEcsService" \
            --query "SecurityGroups[*].GroupId"
    )

    cat <<EOF
    {
        "awsvpcConfiguration": {
            "subnets": ${SUBNET_IDS},
            "securityGroups": ${SECURITY_GROUP_IDS},
            "assignPublicIp": "DISABLED"
        }
    }
EOF
}

function get_container_overrides() {
    # shellcheck disable=SC2001
    COMMAND=$(echo "$@" | sed 's/[^ ][^ ]*/"&"/g' | tr ' ' ',')

    cat <<EOF
    {
        "containerOverrides": [
            {
                "name": "app",
                "command": [${COMMAND}]
            }
        ]
    }
EOF
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        AWS_VPC_CONFIG=$(get_aws_vpc_config)
        CONTAINER_OVERRIDES=$(get_container_overrides "$@")

        aws ecs run-task \
            --cluster "ecsStagingCluster" \
            --count 1 \
            --launch-type "FARGATE" \
            --network-configuration "${AWS_VPC_CONFIG}" \
            --task-definition "StagingApp" \
            --overrides "${CONTAINER_OVERRIDES}"
    fi
fi
